POST  http://localhost:5000/api/catagories/add HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMjM1ODRmLTU1NjYtNDc5Ni04OGU0LTYxMTFhOWZlNWNhOSIsImlzX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6dHJ1ZSwiaWF0IjoxNjAxMTQ4OTQ3fQ.88hP-rz5Txatqy4J9YCTXwfNM0zp2aOflLewGgNC40Y
content-type: application/json

{
    "catagory_name": "Restaurants"
}

###

GET  http://localhost:5000/api/catagories/getall HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMjM1ODRmLTU1NjYtNDc5Ni04OGU0LTYxMTFhOWZlNWNhOSIsImlzX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6dHJ1ZSwiaWF0IjoxNjAxMTQ4OTQ3fQ.88hP-rz5Txatqy4J9YCTXwfNM0zp2aOflLewGgNC40Y
content-type: application/json

###

GET http://localhost:5000/api/catagories/get?catagory_id=18c665a0-78e6-45a9-97d9-63d122389f37 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMjM1ODRmLTU1NjYtNDc5Ni04OGU0LTYxMTFhOWZlNWNhOSIsImlzX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6dHJ1ZSwiaWF0IjoxNjAxMTQ4OTQ3fQ.88hP-rz5Txatqy4J9YCTXwfNM0zp2aOflLewGgNC40Y
content-type: application/json


###
PUT  http://localhost:5000/api/catagories/update HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMjM1ODRmLTU1NjYtNDc5Ni04OGU0LTYxMTFhOWZlNWNhOSIsImlzX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6dHJ1ZSwiaWF0IjoxNjAxMTQ4OTQ3fQ.88hP-rz5Txatqy4J9YCTXwfNM0zp2aOflLewGgNC40Y
content-type: application/json

{
    "catagory_id": "18c665a0-78e6-45a9-97d9-63d122389f37",
    "catagory_name": "Restaurant"
}

###
DELETE  http://localhost:5000/api/catagories/delete HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMjM1ODRmLTU1NjYtNDc5Ni04OGU0LTYxMTFhOWZlNWNhOSIsImlzX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6dHJ1ZSwiaWF0IjoxNjAxMTQ4OTQ3fQ.88hP-rz5Txatqy4J9YCTXwfNM0zp2aOflLewGgNC40Y
content-type: application/json

{
    "catagory_id": "9acfcc4f-fe53-4f50-a361-b73013c9fd2e"
}
