###
POST  http://localhost:5000/api/supplier/requestpin HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlNzc1MjAzLTQwOGYtNGI4MS05YjliLTgxMjEwM2JjOTlkMCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjAyMDc4MzY1LCJleHAiOjE2MDIwNzkyNjV9.yHHhMSr2D4J1d80y9XJT8KNLEIuGnbAxibCImH__tPA
content-type: application/json

{
    "email_id": "theonlysamir@gmail.com"
}

###
PUT  http://localhost:5000/api/supplier/forgotpassword HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlNzc1MjAzLTQwOGYtNGI4MS05YjliLTgxMjEwM2JjOTlkMCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjAyMDQ1NTE0LCJleHAiOjE2MDIwNDY0MTR9.MfUByoupAn45gJmKCuZ0Z4VKeZhgghKFaWKO48ITTD4
content-type: application/json

{
    "email_id": "theonlysamir@gmail.com",
    "pin": "c1969ac4b1ec67c8",
    "new_password": "theonlysamir"
}