GET  http://localhost:5000/api/supplier/orders/getall HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1ZDUxZjNhLTdkNzgtNDNlMy05ZDFiLTE2MTViYzUwMTQ1MiIsInJvbGUiOiJzdXBwbGllciIsImlhdCI6MTYwMjIyNTgzOX0.jo2knaUQEorzHzQQtPHl0QaszP9HYJ-tt1VnSF5ZdXk
content-type: application/json