POST  http://localhost:5000/api/user/orders/add HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlNzc1MjAzLTQwOGYtNGI4MS05YjliLTgxMjEwM2JjOTlkMCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjAyMjI1NTEzLCJleHAiOjE2MDIyMzQ1MTN9.C6H9bIaR3RvSTlppMPV9I8wQaCboWP4cmNII8gVTGtc
content-type: application/json

{
    "address_id": "a5443595-8747-4e29-b0fe-f8dc473d5f49",
    "orders":
        [{
            "product_id": "4408b26f-c5c2-4b23-a222-2c1277ed6c3d",
            "quantity": "2"
        },
        {
            "product_id": "fe666217-ae64-4f0d-b608-437ebcdbf676",
            "quantity": "1"
        }]
    
}

###
 
GET  http://localhost:5000/api/user/orders/getall HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlNzc1MjAzLTQwOGYtNGI4MS05YjliLTgxMjEwM2JjOTlkMCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjAyMjI1NTEzLCJleHAiOjE2MDIyMzQ1MTN9.C6H9bIaR3RvSTlppMPV9I8wQaCboWP4cmNII8gVTGtc
content-type: application/json

###
GET  http://localhost:5000/api/user/orders/get?order_id=df201519-858f-44fb-8145-083045128cc9 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlNzc1MjAzLTQwOGYtNGI4MS05YjliLTgxMjEwM2JjOTlkMCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjAyMjI1NTEzLCJleHAiOjE2MDIyMzQ1MTN9.C6H9bIaR3RvSTlppMPV9I8wQaCboWP4cmNII8gVTGtc
content-type: application/json

###

PUT  http://localhost:5000/api/user/orders/cancel HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlNzc1MjAzLTQwOGYtNGI4MS05YjliLTgxMjEwM2JjOTlkMCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjAyMjI1NTEzLCJleHAiOjE2MDIyMzQ1MTN9.C6H9bIaR3RvSTlppMPV9I8wQaCboWP4cmNII8gVTGtc
content-type: application/json

{
    "order_id": "df201519-858f-44fb-8145-083045128cc9"
}

